name: Android CI

on:
  push:
    branches: [ main ]  # Trigger on push to main branch
  pull_request:
    branches: [ main ]  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: List directory contents
      run: ls -R # This will list all the files in your repository to check gradlew path

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew # Ensure this points to the gradlew file in the root directory

    - name: Build Project
      run: ./gradlew build # Ensure this command runs the Gradle build with the gradlew file

    - name: Run Tests
      run: ./gradlew test # Run tests with gradlew file
